language: node_js
node_js:
  - "8"
cache:
  directories:
    - ~/.npm
    - node_modules
    - ~/.cache/Cypress
before_install:
  - sudo apt-get update
  - sudo apt-get install -y libgconf-2-4
install:
  - npm install
script:
  - npm run ci
